config/routes.rb
Slackbot::Application.routes.draw do
  resources :services

  post "callback/gitlab"
  post "callback/heroku"
  post "callback/custom"
  post "callback/logentries"
  match 'callback/:service', to: 'callback#index', as: :callback, via: [:get, :post]

  root 'services#index'

end

app/models/custom.rb
class Custom
  def self.exec params
    url = Slackbot::SLACK_HOOK

    channel = "#{params[:room]}"
    if params[:is_channel]
      channel = "\##{channel}"
    elsif params[:is_person]
      channel = "@#{channel}"
    end
    payload = {
      channel: channel,
      text: "#{params[:text]}"
    }
    opts = {:body => payload.to_json}
    HTTParty.post(url, opts)
  end
end

app/models/gitlab.rb
class Gitlab
  def self.exec params
    url = Slackbot::SLACK_HOOK

    commit_string = params[:total_commits_count] > 1 ? "commits" : "commit"

    attachments = params[:commits].map do |commit|
      {
        color: "good",
        fields: [{
            title: "#{commit[:message]}",
            value: "<#{commit[:url]}|#{commit[:id][0..9]}>",
            short: false
        }]
      }
    end

    channel = "#{params[:room]}"
    if params[:is_channel]
      channel = "\##{channel}"
    elsif params[:is_person]
      channel = "@#{channel}"
    end
    branch = params[:ref][params[:ref] =~ /[^\/]+$/..-1]
    branch_url = "#{params[:repository][:homepage]}/commits/#{branch}"
    payload = {
      channel: channel,
      text: "#{params[:user_name]} pushes #{params[:total_commits_count]} #{commit_string} to <#{branch_url}|#{branch}> on <#{params[:repository][:homepage]}|#{params[:repository][:name]}>",
      attachments: attachments
    }
    opts = {:body => payload.to_json}
    HTTParty.post(url, opts)
  end
end

app/models/heroku.rb
class Heroku
  def self.exec params
    url = Slackbot::SLACK_HOOK

    comments = params[:git_log].split("\n").map{|line| line.split(':')[1..-1].join}
    attachments = comments.map do |comment|
      {
        color: "#29264d",
        fields: [{
            title: "#{comment}",
            short: false
        }]
      }
    end
    channel = "#{params[:room]}"
    if params[:is_channel]
      channel = "\##{channel}"
    elsif params[:is_person]
      channel = "@#{channel}"
    end
    payload = {
      channel: channel,
      text: "#{params[:user]} deployed version #{params[:release]} of <#{params[:url]}|#{params[:app]}>",
      attachments: attachments
    }
    opts = {:body => payload.to_json}
    HTTParty.post(url, opts)
  end
end

app/models/logentries.rb
class Logentries
  def self.exec params
    url = Slackbot::SLACK_HOOK
    raw_payload = JSON.parse(params[:payload]).with_indifferent_access
    attachments = [
      {
        color: "#29264d",
        fields: [{
            title: "#{raw_payload[:event][:m]}",
            short: false
        }]
      }
    ]

    channel = "#{params[:room]}"
    if params[:is_channel]
      channel = "\##{channel}"
    elsif params[:is_person]
      channel = "@#{channel}"
    end

    if channel.blank?
      channel = "cems-notification"
    end

    payload = {
      channel: channel,
      text: "#{raw_payload[:alert][:name]}",
      attachments: attachments
    }
    opts = {:body => payload.to_json}
    HTTParty.post(url, opts)
  end
end

app/models/runner.rb
class Runner
  attr_reader :service, :params

  def initialize service, params
    @service = service
    @params = params
    instance_eval(@service.helper_methods)
  end

  def channel
    if params[:is_channel]
      "\##{params[:room]}"
    elsif params[:is_person]
      "@#{params[:room]}"
    else
      params[:room]
    end
  end

  def text
    eval(@service.text)
  end

  def attachments
    eval(@service.attachments)
  end

  def payload
    payload = {
      channel: channel,
      text: text,
      attachments: attachments
    }
  end

  def run
    opts = {:body => payload.to_json}
    HTTParty.post(Slackbot::SLACK_HOOK, opts)
  end
end

app/models/service.rb
class Service < ActiveRecord::Base

  before_save :generate_slug

  def run params
    save_sample_params params
    begin
      Runner.new(self, params).run
    rescue => e

    end
  end

  def have_sample_params?
    sample_params.present?
  end

  def save_sample_params params
    self.sample_params = params.to_json
    save
  end

  def test
    run JSON.parse(sample_params, {:symbolize_names => true}) if have_sample_params?
  end

  private
  def generate_slug
    self.slug = title.underscore
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session
  # instead.
  protect_from_forgery with: :null_session
end

app/controllers/callback_controller.rb
class CallbackController < ApplicationController
  def index
    service = Service.find_by(:slug => params[:service])
    # result = 'Something went wrong'
    # if service && service.run(params)
    service && service.run(params)
      # result = 'success'
    # end

    render json: {success: true}
  end

  def gitlab
    Gitlab.exec params
    render text: 'success'
  end

  def heroku
    Heroku.exec params
    render text: 'success'
  end

  def logentries
    Logentries.exec params
    render text: 'success'
  end

  def custom
    Custom.exec params
    render text: 'success'
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to edit_service_path(@service), notice: 'Service was successfully created.' }
        format.json { render action: 'show', status: :created, location: @service }
      else
        format.html { render action: 'new' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        @service.test
        format.html { redirect_to edit_service_path(@service), notice: 'Service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:title, :text, :attachments, :helper_methods, :sample_params)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def service_url service
    DOMAIN + callback_path(service.slug)
  end
end

app/helpers/callback_helper.rb
module CallbackHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/callback/gitlab.html.erb
<h1>Callback#gitlab</h1>
<p>Find me in app/views/callback/gitlab.html.erb</p>

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Yui"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"



  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href=root_path Yui

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield

app/views/services/_code.html.slim
.file-content.code
  div.highlighted-data
  .highlight
    pre
      code
        = blob.data

app/views/services/_form.html.slim
= simple_form_for(@service, html: {class: 'form-horizontal'}) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
  - if @service.persisted?
    .col-lg-6
      label Text
      = f.input :text, input_html: {class: 'tl-editor', data: {editor: 'ruby'}}, wrapper: :nowrapper

      label Attachments
      = f.input :attachments, input_html: {class: 'tl-editor', data: {editor: 'ruby'}}, wrapper: :nowrapper

      label Helper
      = f.input :helper_methods, input_html: {class: 'helper-editor', data: {editor: 'ruby'}}, wrapper: :nowrapper

    .col-lg-6
      label Sample Params
      = f.input :sample_params, input_html: {class: 'params-editor', data: {context: @service.sample_params, editor: 'json'}}, wrapper: :nowrapper

  .form-actions
    = f.button :submit, value: "#{@service.persisted? ? 'Test' : 'Create'}", class: 'btn btn-primary pull-right'

app/views/services/edit.html.slim
.row
  .pull-right
    =link_to 'Back', services_path, class: 'btn btn-default'
.row
  h1= "Editing #{@service.title}"

  p Use this callback link to use in your callback server
  .row
    label Room
    input#room
  .row
    button.btn.btn-primary#submit Generate link

  h3#call_back_url.danger

  - if @service.have_sample_params?
    == render 'form'

  javascript:
    $('#submit').click(function(){
      var link = "#{service_url(@service)}" + "?room=" + $('#room').val();
      $('#call_back_url').text(link);
    });

app/views/services/index.html.slim
.row
  .pull-right
    = link_to 'New Service', new_service_path, class: 'btn btn-primary'

h1 Listing services

.row
  table.table
    thead
      tr
        th Title
        th

    tbody
      - @services.each do |service|
        tr
          td = service.title
          td.pull-right
            = link_to 'Edit', edit_service_path(service), class: 'btn btn-default'
            = link_to 'Destroy', service, data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'btn btn-danger'

app/views/services/new.html.slim
h1 New service

== render 'form'

app/views/services/show.html.slim
p#notice = notice

h3= @service.title

.row
  label= service_url(@service)

.row
  .col-lg-6
    .row
      label Text
      #text-editor.editor
        = @service.text
    .row
      label Attachments
      #attachments-editor.editor
        = @service.attachments
    .row
      label Helper Methods
      #helpers-editor.editor
        = @service.helper_methods
  .col-lg-6
    .row
      label Sample params
      #params-editor.editor data-params=@service.sample_params